# Basic information
name: Ammar Alakkad
tagline: Web Developer
description: "Web Developer, Specialized in PHP (Wordpress, Laravel, CodeIgniter) with many front-end technologies like Twitter Bootstrap, Zurb Foundation, Sass, and others."
author :
  name : Ammar Alakkad
  email : am.alakkad@gmail.com
  github : AAlakkad
  twitter : Am_Alakkad
  google: AmmarAlakkad
  linkedin: ammaralakkad

paginate: 5
permalink: :title

url: http://aalakkad.github.io
production_url: http://aalakkad.github.io
assets_path: /assets

atom_path : /atom.xml
rss_path : /rss.xml

comments :
    provider : true
    disqus :
      short_name : aalakkad

analytics :
    provider : true
    google :
        tracking_id : 'UA-46907291-1'