name: Ammar Alakkad
description: Blog
highlighter: pygments
markdown: redcarpet
permalink: /blog/:title/
production_url: http://aalakkad.me
rss_path: /rss.xml
timezone: Asia/Syria
encoding: UTF-8
exclude: [README.md, Vagrantfile]

collections:
    projects:
        output: true
        permalink: /projects/:path/

tracking_id: 'UA-46907291-1'

author:
    name: Ammar Alakkad
    first_name: Ammar
    title: Web Developer
    email: am.alakkad@gmail.com
    social:
        github: AAlakkad
        twitter: Am_Alakkad
        linkedin: ammaralakkad
