name: Ammar Alakkad
description: My personal site
markdown: redcarpet
pygments: true
permalink: /blog/:title/
production_url: http://aalakkad.github.io
rss_path: /rss.xml
timezone: Asia/Syria
encoding: UTF-8
exclude: [README.md]

author:
    name: Ammar Alakkad
    first_name: Ammar
    title: Web Developer
    email: am.alakkad@gmail.com
    social:
        github: AAlakkad
        twitter: Am_Alakkad
        linkedin: ammaralakkad